- type: replace
  path: /instance_groups/name=enterprise-shared/properties/config/settings/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=enterprise-large/properties/config/settings/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=enterprise-medium-ha/properties/config/settings/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=enterprise-large-ha/properties/config/settings/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=deploy-all/properties/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=tests/properties/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=delete-all/properties/application_access_auth_scheme/value
  value: ldap_server

