- type: replace
  path: /instance_groups/name=enterprise-shared/properties/config/settings/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=enterprise-large/properties/config/settings/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=enterprise-medium-ha/properties/config/settings/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=enterprise-large-ha/properties/config/settings/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=standard-medium/properties/config/settings/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=standard-medium-ha/properties/config/settings/application_access_auth_scheme/value
  value: ldap_server
  
# On demand catalog
- type: replace
  path: /instance_groups/name=management/jobs/name=broker/properties/service_catalog/plans/name=enterprise-shared/properties/config/settings/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=management/jobs/name=broker/properties/service_catalog/plans/name=enterprise-large/properties/config/settings/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=management/jobs/name=broker/properties/service_catalog/plans/name=enterprise-medium-ha/properties/config/settings/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=management/jobs/name=broker/properties/service_catalog/plans/name=enterprise-large-ha/properties/config/settings/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=management/jobs/name=broker/properties/service_catalog/plans/name=standard-medium/properties/config/settings/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=management/jobs/name=broker/properties/service_catalog/plans/name=standard-medium-ha/properties/config/settings/application_access_auth_scheme/value
  value: ldap_server
  
- type: replace
  path: /instance_groups/name=deploy-all/properties/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=tests/properties/application_access_auth_scheme/value
  value: ldap_server
- type: replace
  path: /instance_groups/name=management/jobs/name=delete-all/properties/application_access_auth_scheme/value
  value: ldap_server

